### ISSUE TITLE
Cat Logo link to petprofilepage/login causes blank page

### ISSUE THREAD

**Issue by jay-newman** [Capstone-Projects-2023-Spring/project-virtual-pet#36]
**Severity:** Low

**Description:** In various scenarios clicking the cat logo will try to route to main page then login page and the the result is a blank login page that has to be refreshed to be rendered. This will also occur if a the link is clicked from the login page or register page. This was first noticed when registering a new user, login, from pet selection page without selecting a pet - the logo is clicked and the try's to reroute to main page then reroutes to blank login page. 

**Environment:** Ubuntu/Linux OS, Iphone 12

**Steps to reproduce:** Click cat logo from login page, register page, or with a new user in the pet selection page before selecting a pet click the cat logo.

**Expected Result:** Logo should always route to home page if user is logged in and has selected a pet. If pet hasn't been selected then user should be routed to pet selection page. If clicked from Login/Register pages then should redirect to login.

**Actual result:** User is redirected a login route but page is not rendered.

**Comment by Alexander-Russakoff** [comment]
This issue should be resolved
