### ISSUE TITLE
Emails accepted in registration currently don't allow a period or underscore in the address

### ISSUE THREAD

**Issue by mgclay** [Capstone-Projects-2023-Spring/project-virtual-pet#38]
Severity: low

Description: When attempting to register a new user, the email form does not allow periods or underscores within the user's address (e.g. jane.doe@gmail.com).

Environment: Windows 11, iPhone 12 Pro Max

Steps to reproduce: Access the registration page, and enter an email that contains a period/underscore before the @ symbol.

Expected result: Email should be accepted as a valid input.

Actual result: Email is not accepted as a valid input.

**Comment by Alexander-Russakoff** [comment]
This issue should be resolved
